name: Sysdig IaC Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner

    - name: Test API Connection
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        # API 연결 테스트
        echo "Testing API connection..."
        curl -H "Authorization: Bearer $SECURE_API_TOKEN" \
             -H "Content-Type: application/json" \
             https://app.au1.sysdig.com/api/v1/user/me

    - name: Run Sysdig IaC Scanner
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        echo "Token length: ${#SECURE_API_TOKEN}"
        ./sysdig-cli-scanner --iac --apiurl https://app.au1.sysdig.com .
