name: Sysdig Docker Image Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'vote/Dockerfile'
      - 'result/Dockerfile'
      - 'worker/Dockerfile'

jobs:
  scan-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner

    - name: Create results directory
      run: mkdir -p docker-scan-results

    - name: Build and Scan vote image
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        docker build -t vote-image:latest -f vote/Dockerfile vote/
        ./sysdig-cli-scanner --image vote-image:latest --apiurl https://app.au1.sysdig.com > docker-scan-results/vote.result 2>&1 || true

    - name: Build and Scan result image
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        docker build -t result-image:latest -f result/Dockerfile result/
        ./sysdig-cli-scanner --image result-image:latest --apiurl https://app.au1.sysdig.com > docker-scan-results/result.result 2>&1 || true

    - name: Build and Scan worker image
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        docker build -t worker-image:latest -f worker/Dockerfile worker/
        ./sysdig-cli-scanner --image worker-image:latest --apiurl https://app.au1.sysdig.com > docker-scan-results/worker.result 2>&1 || true

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docker-scan-results/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add Sysdig Docker scan results"
          git push
        fi
