name: Sysdig IaC Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Sysdig CLI Scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner"
        chmod +x ./sysdig-cli-scanner

    - name: Create results directory
      run: mkdir -p k8s-specifications/results

    - name: Run Sysdig IaC Scanner
      env:
        SECURE_API_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        for yaml_file in k8s-specifications/*.yaml k8s-specifications/*.yml; do
          if [ -f "$yaml_file" ]; then
            filename=$(basename "$yaml_file")
            echo "Scanning $filename..."
            ./sysdig-cli-scanner --iac --apiurl https://app.au1.sysdig.com "$yaml_file" > "k8s-specifications/results/${filename}.result" 2>&1 || true
          fi
        done

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add k8s-specifications/results/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add Sysdig IaC scan results"
          git push
        fi
