name: Sysdig IaC Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Sysdig IaC Scanner
      run: |
        curl -sSL https://download.sysdig.com/IaCScanner/install | bash

    - name: Run Sysdig IaC Scanner
      env:
        SYSDIG_SECURE_TOKEN: ${{ secrets.SYSDIG_SECURE_TOKEN }}
      run: |
        ./iac-scanner scan -d . --sysdig-token $SYSDIG_SECURE_TOKEN

